# Project config
PROJ := state-machines

PROJ_DEPS :=
PROJ_RTL_SRCS := $(addprefix rtl/, \
	slowclock.v \
)
PROJ_TOP_SRC := rtl/main.v
PROJ_TOP_MOD := top

# Include default rules
include ../_common/build.mk